stages:
  - dependencies
  - lint
  - test
  - build
  - deploy

image: robert96/ember-js

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - node_modules
    - bower_components

install_dependencies:
  stage: dependencies
  script:
    - npm install -g ember-cli
    - npm install --only=dev
    - npm update

lint:
  stage: lint
  script:
    - npm run lint:hbs
    - npm run lint:js

test:
  stage: test
  script:
    - ember test

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - ember build --environment production

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
  - master
